package data_enum

enum class CardErrorDataEnum(val data: String) {
	TAG_00("Approved"),
	TAG_01("Refer To Issuer"),
	TAG_02("Refer To Issuer, special condition"),
	TAG_03("Invalid Merchant ID"),
	TAG_04("Pick Up Card"),
	TAG_05("Do Not Honour"),
	TAG_06("Error"),
	TAG_07("Pick Up Card, special condition"),
	TAG_08("Check Signature/Id or Honor with ID"),
	TAG_10("Partial Approval"),
	TAG_11("VIP Approval"),
	TAG_12("Invalid Transaction"),
	TAG_13("Invalid Amount"),
	TAG_14("Invalid Card No"),
	TAG_15("Invalid Issuer"),
	TAG_16("Approved to update track 3 (Reserved)"),
	TAG_17("Customer Cancellation (Reversal only)"),
	TAG_19("Re-enter Transaction"),
	TAG_21("No Transactions"),
	TAG_22("Related Transaction Error; Suspected Malfunction"),
	TAG_24("Invalid Currency Code"),
	TAG_25("Terminated/Inactive card"),
	TAG_30("Message Format Error"),
	TAG_31("Bank ID Not Found"),
	TAG_32("Partial Reversal"),
	TAG_38("PIN Try Limit Exceeded"),
	TAG_41("Card Reported Lost"),
	TAG_43("Stolen Card"),
	TAG_44("PIN Change Require"),
	TAG_45("Card Not Activated For Use"),
	TAG_46("Please Insert Card or Try Another Card"),
	TAG_51("Insufficient Fund"),
	TAG_52("No Checking Account"),
	TAG_53("No Savings Account"),
	TAG_54("Expired Card"),
	TAG_55("Invalid PIN"),
	TAG_56("Invalid Card"),
	TAG_57("Transaction Not Permitted to Cardholder"),
	TAG_58("Transaction Not Permitted to Terminal"),
	TAG_59("Suspected Fraud"),
	TAG_61("Over Limit"),
	TAG_62("Restricted Card"),
	TAG_63("Security Violation"),
	TAG_64("Transaction does not fulfill AML requirement"),
	TAG_65("Exceeds Withdrawal Count Limit"),
	TAG_70("Contact Card Issuer"),
	TAG_71("PIN not changed"),
	TAG_75("PIN Tries Exceeded"),
	TAG_76("Invalid Description Code"),
	TAG_77("Reconcile Error"),
	TAG_78("Invalid Trace/TMK Reference No"),
	TAG_79("Batch Already Open"),
	TAG_80("Invalid Batch No"),
	TAG_82("CVV Validation Error"),
	TAG_85("Batch Not Found"),
	TAG_86("PIN Validation Not Possible"),
	TAG_87("Purchase Amount Only, No Cash Back Allowed"),
	TAG_88("Cryptographic Failure, Call Issuer"),
	TAG_89("Invalid Terminal ID"),
	TAG_91("Issuer/Switch Inoperative"),
	TAG_92("Destination Cannot Be Found for Routing"),
	TAG_93("Transaction cannot be completed; violation of law"),
	TAG_94("Duplicate Transaction"),
	TAG_95("Total Mismatch"),
	TAG_96("System Malfunction/Error"),
	TAG_98("Issuer Response Not Receive by UnionPay"),
	TAG_99("Declined"),
//	TAG_E1("Invalid Parameter"),
//	TAG_E2("Auto Settlement is running"),
//	TAG_E3("No Batch to Settle"),
//	TAG_E4("Settlement Fail"),
//	TAG_E5("User Cancel the Transaction"),
//	TAG_E6("Timeout"),
//	TAG_E7("Terminal System Error"),
	TAG_B1("Do Not Allow Attempt"),
	TAG_C1("Channel not found"),
	TAG_C2("Invalid Terminal"),
	TAG_C3("Inactive Terminal"),
	TAG_C4("Routing Not Allowed"),
	TAG_D1("Incorrect Key ID"),
	TAG_D2("Incorrect TLE Header Length"),
	TAG_D3("TLE Header Not Found"),
	TAG_D4("Routing Disabled By the Administrator"),
	TAG_D5("Requesting Algorithm Not Enabled"),
	TAG_C8("Incorrect Key Check Value"),
	TAG_E1("MAC Failed"),
	TAG_E2("Channel Error"),
	TAG_E3("Requesting NII not registered"),
	TAG_E4("Invalid Data in Request"),
	TAG_E8("PIN Tries Exceed"),
	TAG_E9("Key Downloading Exceed"),
	TAG_F3("TLE Server Busy"),
	TAG_F4("Smart Card Blocked"),
	TAG_F8("Invalid BDK"),
	TAG_F9("Invalid KSN"),
	TAG_G1("Host Timeout"),
	TAG_G2("HSM Error Found"),
	TAG_SHC001("Invalid Parameter"),
	TAG_SHC002("Auto Settlement is running"),
	TAG_SHC003("No Batch to Settle"),
	TAG_SHC004("Settlement Fail"),
	TAG_SHC005("User Cancel the Transaction"),
	TAG_SHC006("Timeout"),
	TAG_SHC007("Terminal System Error"),
	TAG_SHC008("Transaction Not Found"),
	TAG_SHC009("Payment Session Terminated"),
	TAG_SHC010("Transaction Not Supported"),
	TAG_SHC011("Please Run Settlement for Last day Transaction before Proceed"),
	TAG_ZQ("PIN Not Entered"),
	TAG_ZR("Card Does Not Match Pre-Auth Card"),
	// Set only by the StorageGuard blocks. Without its own code the blocked-sale screen
	// inherits whatever the ISO layer last set — on MF919 that read "Empty Secure Key", pointing
	// the merchant at key injection instead of storage.
	TAG_ZS("Storage Full - Contact Support"),
	TAG_ZT("Transaction Reversal"),
	TAG_ZU("Timeout"),
	TAG_ZV("Empty Secure Key"),
	TAG_ZW("Card Declined Transaction"),
	TAG_ZX("Please insert or try another card"),
	TAG_ZY("Please insert card"),
	TAG_ZZ("Card Not Supported")
}