package com.sc.mf919.kotlin.database.model

/**
 * bnplPayTable models. Field order mirrors the column order in
 * DatabaseTables.BNPL_PAY_TABLE (id first) so positional row arrays built from
 * DbModelBnplPayTable line up with the legacy String[] the UI expects.
 * postingDt is generated by the repo on insert (was done in the old Database layer).
 */
data class DbModelBnplPayTableInsert(
    val postingDt: String,
    val txnType: String?,
    val payBrand: String?,
    val payBrandDesc: String?,
    val txnDt: String?,
    val seqNo: String?,
    val mid: String?,
    val tid: String?,
    val txnAmt: String?,
    val refId: String?,
    val hostRefNo: String?,
    val txnRefNo: String?,
    val status: String?,
    val addInfo: String?,
    val acqCode: String?,
    val txnApprCode: String?,
    val packageCode: String?,
    val paymentType: String?,
    val tenure: String?,
    val tenureDesc: String?,
    val bnplResp: String?
)

data class DbModelBnplPayTable(
    val id: Int,
    val postingDt: String,
    val txnType: String,
    val payBrand: String,
    val payBrandDesc: String,
    val txnDt: String,
    val seqNo: String,
    val mid: String,
    val tid: String,
    val txnAmt: String,
    val refId: String,
    val hostRefNo: String,
    val txnRefNo: String,
    val status: String,
    val addInfo: String,
    val acqCode: String,
    val txnApprCode: String,
    val packageCode: String,
    val paymentType: String,
    val tenure: String,
    val tenureDesc: String,
    val bnplResp: String
)
