package com.sc.mf919.kotlin.database.model

/**
 * printReceiptBnpl models. Field order mirrors the column order in
 * DatabaseTables.PRINT_RECEIPT_BNPL (id first) so positional row arrays built from
 * DbModelPrintReceiptBnpl line up with the legacy String[] the UI expects.
 * postingDt is generated by the repo on insert (was done in the old Database layer).
 */
data class DbModelPrintReceiptBnplInsert(
    val postingDt: String,
    val txnType: String?,
    val payBrand: String?,
    val payBrandDesc: String?,
    val txnDt: String?,
    val mid: String?,
    val tid: String?,
    val txnAmt: String?,
    val refId: String?,
    val hostRefNo: String?,
    val txnRefNo: String?,
    val respCode: String?,
    val status: String?,
    val addInfo: String?,
    val printInfo: String?,
    val acqCode: String?,
    val txnApprCode: String?,
    val tenure: String?,
    val tenureDesc: String?,
    val bnplResp: String?
)

data class DbModelPrintReceiptBnpl(
    val id: Int,
    val postingDt: String,
    val txnType: String,
    val payBrand: String,
    val payBrandDesc: String,
    val txnDt: String,
    val mid: String,
    val tid: String,
    val txnAmt: String,
    val refId: String,
    val hostRefNo: String,
    val txnRefNo: String,
    val respCode: String,
    val status: String,
    val addInfo: String,
    val printInfo: String,
    val acqCode: String,
    val txnApprCode: String,
    val tenure: String,
    val tenureDesc: String,
    val bnplResp: String
)
