package tms.models

data class TerminalConfigReq (
	val SEQ_NO: String?,
	val TXN_DT: String?,
	val DEV_SN: String?,
	val DEV_MODEL: String?,
	val DEV_APPNAME: String?,
	val DEV_PROJECT: String?,
	val DEV_LOCATION: String?,
	val ADD_INFO: String?,
	val MC_VER: String?
)

data class TerminalConfigResp (
	val SEQ_NO: String?,
	val RESP_CODE: String?,
	val RESP_DESC: String?,
	val CONTACT: Int,
	val CONTACTLESS: Int,
	val MAGSTRIPE: Int,
	val FORCE_PIN: Int,
	val ISO_PRINT: Int,
	val RECEIPT_PRINT: Int,
	val SALE: Int,
	val VOID: Int,
	val PREAUTH: Int,
	val SALECOM: Int,
	val SALECOM_ONLINE: Int,
	val REFUND: Int,
	val OPT_IN: Int,
	val TMS_RECEIPT: Int,
	val TMS_ENABLE: Int,
	val AUTO_SETTLEMENT: Int,
	val QR_PAY: Int,
	val POWERED_BY: String?,
	val POWERED_BY_BW: String?,
	val HOME_LOGO: String?,
	val MC_VER: String?,
	val DEV_PROJECT: String?,
	val DEV_LOCATION: String?,
	val DEV_LANE_ID: String?,
	val THIRD_APP_NAME: String?,
	val THIRD_APP_PACKNAME: String?,
	val VOID_WITH_PIN: Int,
	val MOTO: Int,
	val TIMEOUT_SECONDS: Int,
	val SETTLEMENT_WITH_PIN: Int,
	val REMOTE_DOWNLOAD_BSN_KEY: Int,
	val EWALLET_PRODUCT_LIST: Any?,
	val FORCE_LOCK_HOME: Int,
	val FORCE_SETTLEMENT: Int,
	val UNATTENDED_MODE: Int,
	val CABLE_CONNECTION_METHOD: String?,
	val FORCE_SETTLEMENT_DAILY: String?,
	val CASHOUT: String?,
	val ISO_WEBSOCKET: String?,
	val WEBSOCKET: String?,
	val SALES_CARD: String?,
	val SALES_EWALLET: String?,
	val DENOMINATION: String?,
	val RECEIPT_MERCHANT_INFO_SIZE: String? = null,
	val RECEIPT_TXN_INFO_SIZE: String? = null,
)

data class EWProducts(
	var PRODUCT_CODE: String,
	var PRODUCT_NAME: List<String>,
	var PRODUCT_SEQ: Int,
)
